name: barchart.com API Ruby Client
on:
  pull_request:
    paths:
      - '**'
  push:
    paths:
      - '**'

defaults:
  run:
    working-directory: ./barchart

jobs:
  test:
    name: Build, rubocop, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          bundler-cache: true
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run rspec
        run: bundle exec rspec
